
static char svga_cmd_tables[][64] = {
	"SVGA_3D_CMD_SURFACE_DEFINE",
	"SVGA_3D_CMD_SURFACE_DESTROY",
	"SVGA_3D_CMD_SURFACE_COPY",
	"SVGA_3D_CMD_SURFACE_STRETCHBLT",
	"SVGA_3D_CMD_SURFACE_DMA",
	"SVGA_3D_CMD_CONTEXT_DEFINE",
	"SVGA_3D_CMD_CONTEXT_DESTROY",
	"SVGA_3D_CMD_SETTRANSFORM",
	"SVGA_3D_CMD_SETZRANGE",
	"SVGA_3D_CMD_SETRENDERSTATE",
	"SVGA_3D_CMD_SETRENDERTARGET",
	"SVGA_3D_CMD_SETTEXTURESTATE",
	"SVGA_3D_CMD_SETMATERIAL",
	"SVGA_3D_CMD_SETLIGHTDATA",
	"SVGA_3D_CMD_SETLIGHTENABLED",
	"SVGA_3D_CMD_SETVIEWPORT",
	"SVGA_3D_CMD_SETCLIPPLANE",
	"SVGA_3D_CMD_CLEAR",
	"SVGA_3D_CMD_PRESENT",
	"SVGA_3D_CMD_SHADER_DEFINE",
	"SVGA_3D_CMD_SHADER_DESTROY",
	"SVGA_3D_CMD_SET_SHADER",
	"SVGA_3D_CMD_SET_SHADER_CONST",
	"SVGA_3D_CMD_DRAW_PRIMITIVES",
	"SVGA_3D_CMD_SETSCISSORRECT",
	"SVGA_3D_CMD_BEGIN_QUERY",
	"SVGA_3D_CMD_END_QUERY",
	"SVGA_3D_CMD_WAIT_FOR_QUERY",
	"SVGA_3D_CMD_PRESENT_READBACK",
	"SVGA_3D_CMD_BLIT_SURFACE_TO_SCREEN",
	"SVGA_3D_CMD_SURFACE_DEFINE_V2",
	"SVGA_3D_CMD_GENERATE_MIPMAPS",
	"SVGA_UNK_1072",
	"SVGA_UNK_1073",
	"SVGA_UNK_1074",
	"SVGA_UNK_1075",
	"SVGA_UNK_1076",
	"SVGA_UNK_1077",
	"SVGA_UNK_1078",
	"SVGA_UNK_1079",
	"SVGA_3D_CMD_ACTIVATE_SURFACE",
	"SVGA_3D_CMD_DEACTIVATE_SURFACE",
	"SVGA_3D_CMD_SCREEN_DMA",
	"SVGA_3D_CMD_DEAD1",
	"SVGA_3D_CMD_DEAD2",
	"SVGA_3D_CMD_DEAD12",
	"SVGA_3D_CMD_DEAD13",
	"SVGA_3D_CMD_DEAD14",
	"SVGA_3D_CMD_DEAD15",
	"SVGA_3D_CMD_DEAD16",
	"SVGA_3D_CMD_DEAD17",
	"SVGA_3D_CMD_SET_OTABLE_BASE",
	"SVGA_3D_CMD_READBACK_OTABLE",
	"SVGA_3D_CMD_DEFINE_GB_MOB",
	"SVGA_3D_CMD_DESTROY_GB_MOB",
	"SVGA_3D_CMD_DEAD3",
	"SVGA_3D_CMD_UPDATE_GB_MOB_MAPPING",
	"SVGA_3D_CMD_DEFINE_GB_SURFACE",
	"SVGA_3D_CMD_DESTROY_GB_SURFACE",
	"SVGA_3D_CMD_BIND_GB_SURFACE",
	"SVGA_3D_CMD_COND_BIND_GB_SURFACE",
	"SVGA_3D_CMD_UPDATE_GB_IMAGE",
	"SVGA_3D_CMD_UPDATE_GB_SURFACE",
	"SVGA_3D_CMD_READBACK_GB_IMAGE",
	"SVGA_3D_CMD_READBACK_GB_SURFACE",
	"SVGA_3D_CMD_INVALIDATE_GB_IMAGE",
	"SVGA_3D_CMD_INVALIDATE_GB_SURFACE",
	"SVGA_3D_CMD_DEFINE_GB_CONTEXT",
	"SVGA_3D_CMD_DESTROY_GB_CONTEXT",
	"SVGA_3D_CMD_BIND_GB_CONTEXT",
	"SVGA_3D_CMD_READBACK_GB_CONTEXT",
	"SVGA_3D_CMD_INVALIDATE_GB_CONTEXT",
	"SVGA_3D_CMD_DEFINE_GB_SHADER",
	"SVGA_3D_CMD_DESTROY_GB_SHADER",
	"SVGA_3D_CMD_BIND_GB_SHADER",
	"SVGA_3D_CMD_SET_OTABLE_BASE64",
	"SVGA_3D_CMD_BEGIN_GB_QUERY",
	"SVGA_3D_CMD_END_GB_QUERY",
	"SVGA_3D_CMD_WAIT_FOR_GB_QUERY",
	"SVGA_3D_CMD_NOP",
	"SVGA_3D_CMD_ENABLE_GART",
	"SVGA_3D_CMD_DISABLE_GART",
	"SVGA_3D_CMD_MAP_MOB_INTO_GART",
	"SVGA_3D_CMD_UNMAP_GART_RANGE",
	"SVGA_3D_CMD_DEFINE_GB_SCREENTARGET",
	"SVGA_3D_CMD_DESTROY_GB_SCREENTARGET",
	"SVGA_3D_CMD_BIND_GB_SCREENTARGET",
	"SVGA_3D_CMD_UPDATE_GB_SCREENTARGET",
	"SVGA_3D_CMD_READBACK_GB_IMAGE_PARTIAL",
	"SVGA_3D_CMD_INVALIDATE_GB_IMAGE_PARTIAL",
	"SVGA_3D_CMD_SET_GB_SHADERCONSTS_INLINE",
	"SVGA_3D_CMD_GB_SCREEN_DMA",
	"SVGA_3D_CMD_BIND_GB_SURFACE_WITH_PITCH",
	"SVGA_3D_CMD_GB_MOB_FENCE",
	"SVGA_3D_CMD_DEFINE_GB_SURFACE_V2",
	"SVGA_3D_CMD_DEFINE_GB_MOB64",
	"SVGA_3D_CMD_REDEFINE_GB_MOB64",
	"SVGA_3D_CMD_NOP_ERROR",
	"SVGA_3D_CMD_SET_VERTEX_STREAMS",
	"SVGA_3D_CMD_SET_VERTEX_DECLS",
	"SVGA_3D_CMD_SET_VERTEX_DIVISORS",
	"SVGA_3D_CMD_DRAW",
	"SVGA_3D_CMD_DRAW_INDEXED",
	"SVGA_3D_CMD_DX_DEFINE_CONTEXT",
	"SVGA_3D_CMD_DX_DESTROY_CONTEXT",
	"SVGA_3D_CMD_DX_BIND_CONTEXT",
	"SVGA_3D_CMD_DX_READBACK_CONTEXT",
	"SVGA_3D_CMD_DX_INVALIDATE_CONTEXT",
	"SVGA_3D_CMD_DX_SET_SINGLE_CONSTANT_BUFFER",
	"SVGA_3D_CMD_DX_SET_SHADER_RESOURCES",
	"SVGA_3D_CMD_DX_SET_SHADER",
	"SVGA_3D_CMD_DX_SET_SAMPLERS",
	"SVGA_3D_CMD_DX_DRAW",
	"SVGA_3D_CMD_DX_DRAW_INDEXED",
	"SVGA_3D_CMD_DX_DRAW_INSTANCED",
	"SVGA_3D_CMD_DX_DRAW_INDEXED_INSTANCED",
	"SVGA_3D_CMD_DX_DRAW_AUTO",
	"SVGA_3D_CMD_DX_SET_INPUT_LAYOUT",
	"SVGA_3D_CMD_DX_SET_VERTEX_BUFFERS",
	"SVGA_3D_CMD_DX_SET_INDEX_BUFFER",
	"SVGA_3D_CMD_DX_SET_TOPOLOGY",
	"SVGA_3D_CMD_DX_SET_RENDERTARGETS",
	"SVGA_3D_CMD_DX_SET_BLEND_STATE",
	"SVGA_3D_CMD_DX_SET_DEPTHSTENCIL_STATE",
	"SVGA_3D_CMD_DX_SET_RASTERIZER_STATE",
	"SVGA_3D_CMD_DX_DEFINE_QUERY",
	"SVGA_3D_CMD_DX_DESTROY_QUERY",
	"SVGA_3D_CMD_DX_BIND_QUERY",
	"SVGA_3D_CMD_DX_SET_QUERY_OFFSET",
	"SVGA_3D_CMD_DX_BEGIN_QUERY",
	"SVGA_3D_CMD_DX_END_QUERY",
	"SVGA_3D_CMD_DX_READBACK_QUERY",
	"SVGA_3D_CMD_DX_SET_PREDICATION",
	"SVGA_3D_CMD_DX_SET_SOTARGETS",
	"SVGA_3D_CMD_DX_SET_VIEWPORTS",
	"SVGA_3D_CMD_DX_SET_SCISSORRECTS",
	"SVGA_3D_CMD_DX_CLEAR_RENDERTARGET_VIEW",
	"SVGA_3D_CMD_DX_CLEAR_DEPTHSTENCIL_VIEW",
	"SVGA_3D_CMD_DX_PRED_COPY_REGION",
	"SVGA_3D_CMD_DX_PRED_COPY",
	"SVGA_3D_CMD_DX_PRESENTBLT",
	"SVGA_3D_CMD_DX_GENMIPS",
	"SVGA_3D_CMD_DX_UPDATE_SUBRESOURCE",
	"SVGA_3D_CMD_DX_READBACK_SUBRESOURCE",
	"SVGA_3D_CMD_DX_INVALIDATE_SUBRESOURCE",
	"SVGA_3D_CMD_DX_DEFINE_SHADERRESOURCE_VIEW",
	"SVGA_3D_CMD_DX_DESTROY_SHADERRESOURCE_VIEW",
	"SVGA_3D_CMD_DX_DEFINE_RENDERTARGET_VIEW",
	"SVGA_3D_CMD_DX_DESTROY_RENDERTARGET_VIEW",
	"SVGA_3D_CMD_DX_DEFINE_DEPTHSTENCIL_VIEW",
	"SVGA_3D_CMD_DX_DESTROY_DEPTHSTENCIL_VIEW",
	"SVGA_3D_CMD_DX_DEFINE_ELEMENTLAYOUT",
	"SVGA_3D_CMD_DX_DESTROY_ELEMENTLAYOUT",
	"SVGA_3D_CMD_DX_DEFINE_BLEND_STATE",
	"SVGA_3D_CMD_DX_DESTROY_BLEND_STATE",
	"SVGA_3D_CMD_DX_DEFINE_DEPTHSTENCIL_STATE",
	"SVGA_3D_CMD_DX_DESTROY_DEPTHSTENCIL_STATE",
	"SVGA_3D_CMD_DX_DEFINE_RASTERIZER_STATE",
	"SVGA_3D_CMD_DX_DESTROY_RASTERIZER_STATE",
	"SVGA_3D_CMD_DX_DEFINE_SAMPLER_STATE",
	"SVGA_3D_CMD_DX_DESTROY_SAMPLER_STATE",
	"SVGA_3D_CMD_DX_DEFINE_SHADER",
	"SVGA_3D_CMD_DX_DESTROY_SHADER",
	"SVGA_3D_CMD_DX_BIND_SHADER",
	"SVGA_3D_CMD_DX_DEFINE_STREAMOUTPUT",
	"SVGA_3D_CMD_DX_DESTROY_STREAMOUTPUT",
	"SVGA_3D_CMD_DX_SET_STREAMOUTPUT",
	"SVGA_3D_CMD_DX_SET_COTABLE",
	"SVGA_3D_CMD_DX_READBACK_COTABLE",
	"SVGA_3D_CMD_DX_BUFFER_COPY",
	"SVGA_3D_CMD_DX_TRANSFER_FROM_BUFFER",
	"SVGA_3D_CMD_DX_SURFACE_COPY_AND_READBACK",
	"SVGA_3D_CMD_DX_MOVE_QUERY",
	"SVGA_3D_CMD_DX_BIND_ALL_QUERY",
	"SVGA_3D_CMD_DX_READBACK_ALL_QUERY",
	"SVGA_3D_CMD_DX_PRED_TRANSFER_FROM_BUFFER",
	"SVGA_3D_CMD_DX_MOB_FENCE_64",
	"SVGA_3D_CMD_DX_BIND_ALL_SHADER",
	"SVGA_3D_CMD_DX_HINT",
	"SVGA_3D_CMD_DX_BUFFER_UPDATE",
	"SVGA_3D_CMD_DX_SET_VS_CONSTANT_BUFFER_OFFSET",
	"SVGA_3D_CMD_DX_SET_PS_CONSTANT_BUFFER_OFFSET",
	"SVGA_3D_CMD_DX_SET_GS_CONSTANT_BUFFER_OFFSET",
	"SVGA_3D_CMD_DX_SET_HS_CONSTANT_BUFFER_OFFSET",
	"SVGA_3D_CMD_DX_SET_DS_CONSTANT_BUFFER_OFFSET",
	"SVGA_3D_CMD_DX_SET_CS_CONSTANT_BUFFER_OFFSET",
	"SVGA_3D_CMD_DX_COND_BIND_ALL_SHADER",
	"SVGA_3D_CMD_SCREEN_COPY",
	"SVGA_3D_CMD_RESERVED1",
	"SVGA_3D_CMD_RESERVED2",
	"SVGA_3D_CMD_RESERVED3",
	"SVGA_3D_CMD_RESERVED4",
	"SVGA_3D_CMD_RESERVED5",
	"SVGA_3D_CMD_RESERVED6",
	"SVGA_3D_CMD_RESERVED7",
	"SVGA_3D_CMD_RESERVED8",
	"SVGA_3D_CMD_GROW_OTABLE",
	"SVGA_3D_CMD_DX_GROW_COTABLE",
	"SVGA_3D_CMD_INTRA_SURFACE_COPY",
	"SVGA_3D_CMD_DEFINE_GB_SURFACE_V3",
	"SVGA_3D_CMD_DX_RESOLVE_COPY",
	"SVGA_3D_CMD_DX_PRED_RESOLVE_COPY",
	"SVGA_3D_CMD_DX_PRED_CONVERT_REGION",
	"SVGA_3D_CMD_DX_PRED_CONVERT",
	"SVGA_3D_CMD_WHOLE_SURFACE_COPY",
	"SVGA_3D_CMD_DX_DEFINE_UA_VIEW",
	"SVGA_3D_CMD_DX_DESTROY_UA_VIEW",
	"SVGA_3D_CMD_DX_CLEAR_UA_VIEW_UINT",
	"SVGA_3D_CMD_DX_CLEAR_UA_VIEW_FLOAT",
	"SVGA_3D_CMD_DX_COPY_STRUCTURE_COUNT",
	"SVGA_3D_CMD_DX_SET_UA_VIEWS",
	"SVGA_3D_CMD_DX_DRAW_INDEXED_INSTANCED_INDIRECT",
	"SVGA_3D_CMD_DX_DRAW_INSTANCED_INDIRECT",
	"SVGA_3D_CMD_DX_DISPATCH",
	"SVGA_3D_CMD_DX_DISPATCH_INDIRECT",
	"SVGA_3D_CMD_WRITE_ZERO_SURFACE",
	"SVGA_3D_CMD_UPDATE_ZERO_SURFACE",
	"SVGA_3D_CMD_DX_TRANSFER_TO_BUFFER",
	"SVGA_3D_CMD_DX_SET_STRUCTURE_COUNT",
	"SVGA_3D_CMD_LOGICOPS_BITBLT",
	"SVGA_3D_CMD_LOGICOPS_TRANSBLT",
	"SVGA_3D_CMD_LOGICOPS_STRETCHBLT",
	"SVGA_3D_CMD_LOGICOPS_COLORFILL",
	"SVGA_3D_CMD_LOGICOPS_ALPHABLEND",
	"SVGA_3D_CMD_LOGICOPS_CLEARTYPEBLEND",
	"SVGA_3D_CMD_DX_COPY_COTABLE_INTO_MOB",
	"SVGA_3D_CMD_UPDATE_GB_SCREENTARGET_V2",
	"SVGA_3D_CMD_DEFINE_GB_SURFACE_V4",
	"SVGA_3D_CMD_DX_SET_CS_UA_VIEWS",
	"SVGA_3D_CMD_DX_SET_MIN_LOD",
	"SVGA_UNK_2070",
	"SVGA_UNK_2071",
	"SVGA_3D_CMD_DX_DEFINE_DEPTHSTENCIL_VIEW_V2",
	"SVGA_3D_CMD_DX_DEFINE_STREAMOUTPUT_WITH_MOB",
	"SVGA_3D_CMD_DX_SET_SHADER_IFACE",
	"SVGA_3D_CMD_DX_BIND_STREAMOUTPUT",
	"SVGA_3D_CMD_SURFACE_STRETCHBLT_NON_MS_TO_MS",
	"SVGA_3D_CMD_DX_BIND_SHADER_IFACE",
	"SVGA_3D_CMD_UPDATE_GB_SCREENTARGET_MOVE",
	"SVGA_UNK_2079",
	"SVGA_UNK_2080",
	"SVGA_3D_CMD_DX_PRED_STAGING_COPY",
	"SVGA_3D_CMD_DX_STAGING_COPY",
	"SVGA_3D_CMD_DX_PRED_STAGING_COPY_REGION",
	"SVGA_3D_CMD_DX_SET_VERTEX_BUFFERS_V2",
	"SVGA_3D_CMD_DX_SET_INDEX_BUFFER_V2",
	"SVGA_3D_CMD_DX_SET_VERTEX_BUFFERS_OFFSET_AND_SIZE",
	"SVGA_3D_CMD_DX_SET_INDEX_BUFFER_OFFSET_AND_SIZE",
	"SVGA_3D_CMD_DX_DEFINE_RASTERIZER_STATE_V2",
	"SVGA_3D_CMD_DX_PRED_STAGING_CONVERT_REGION",
	"SVGA_3D_CMD_DX_PRED_STAGING_CONVERT",
	"SVGA_3D_CMD_DX_STAGING_BUFFER_COPY",
};

#define CMD3D_MIN 1040
#define CMD3D_MAX 1291

static char dbg_cmd3d[] = "cmd3D: %s (%d)\n";
static char dbg_cmd3d_trace[] = "cmd3D(%02ld): %s (%ld)\n";
//static char dbg_cmd_fence[] = "cmd FENCE\n";
//static char dbg_cmd_unk[] = "non 3D cmd %d - STOP\n";

void debug_cmdbuf(void *cmdbuf, DWORD cmd_size)
{
	BYTE *ptr = cmdbuf;
	BYTE *ptr_max = ptr + cmd_size;
	
	while(ptr < ptr_max)
	{
		DWORD *cmd = (DWORD*)ptr;
		
		if(*cmd >= CMD3D_MIN && *cmd <= CMD3D_MAX)
		{
			dbg_printf(dbg_cmd3d, svga_cmd_tables[*cmd - CMD3D_MIN], *cmd);
			ptr += *(cmd+1) + 8;
		}
		/*else if(*cmd == SVGA_CMD_FENCE)
		{
			dbg_printf(dbg_cmd_fence);
			ptr += 8;
		}*/
		else
		{
			//dbg_printf(dbg_cmd_unk, *cmd);
			return;
		}
	}
}

#define LAST_CMDS_MAX 16
static DWORD last_cmds[LAST_CMDS_MAX] = {0};
static DWORD last_cmds_pos = 0;

void debug_cmdbuf_trace(void *cmdbuf, DWORD cmd_size, DWORD cmd_to_trace)
{
	BYTE *ptr = cmdbuf;
	BYTE *ptr_max = ptr + cmd_size;
	
	while(ptr < ptr_max)
	{
		DWORD *cmd = (DWORD*)ptr;
		
		if(*cmd >= CMD3D_MIN && *cmd <= CMD3D_MAX)
		{
			DWORD size = *(cmd+1);
			//dbg_printf(dbg_cmd3d, svga_cmd_tables[*cmd - CMD3D_MIN], *cmd);
			last_cmds[last_cmds_pos++] = *cmd;
			last_cmds_pos %= LAST_CMDS_MAX;
			
			if(*cmd == cmd_to_trace)
			{
				DWORD i;
				for(i = 0; i < LAST_CMDS_MAX; i++)
				{
					DWORD c = last_cmds[(last_cmds_pos + i) % LAST_CMDS_MAX];
					dbg_printf(dbg_cmd3d_trace, i, svga_cmd_tables[c - CMD3D_MIN], c);
				}
			}
			
			ptr += size + 8;
		}
		/*else if(*cmd == SVGA_CMD_FENCE)
		{
			dbg_printf(dbg_cmd_fence);
			ptr += 8;
		}*/
		else
		{
			//dbg_printf(dbg_cmd_unk, *cmd);
			return;
		}
	}
}

static char debug_draw_surface[] = "\tSID: %ld\n";

void debug_draw(void *cmdbuf, DWORD cmd_size)
{
	BYTE *ptr = cmdbuf;
	BYTE *ptr_max = ptr + cmd_size;
	
	while(ptr < ptr_max)
	{
		DWORD *cmd = (DWORD*)ptr;
		
		switch(*cmd)
		{
			case SVGA_3D_CMD_DX_DRAW:
			case SVGA_3D_CMD_DX_DRAW_INDEXED:
			case SVGA_3D_CMD_DX_BEGIN_QUERY:
			case SVGA_3D_CMD_DX_END_QUERY:
			case SVGA_3D_CMD_READBACK_GB_SURFACE:
			case SVGA_3D_CMD_SURFACE_DMA:
			case SVGA_3D_CMD_UPDATE_GB_SURFACE:
			case SVGA_3D_CMD_UPDATE_GB_SCREENTARGET:
				dbg_printf(dbg_cmd3d, svga_cmd_tables[*cmd - CMD3D_MIN], *cmd);
				break;
			case SVGA_3D_CMD_BLIT_SURFACE_TO_SCREEN:
				dbg_printf(dbg_cmd3d, svga_cmd_tables[*cmd - CMD3D_MIN], *cmd);
				dbg_printf(debug_draw_surface, *(cmd+2));
				break;
			case SVGA_3D_CMD_DX_SET_SOTARGETS:
				{
					DWORD i;
					DWORD size = (*(cmd+1))/4 + 2;
					dbg_printf(dbg_cmd3d, svga_cmd_tables[*cmd - CMD3D_MIN], *cmd);
					// 0: cmd
					// 1: size
					// 2: pad
					for(i = 3; i < size; i += (sizeof(SVGA3dSoTarget)/4) )
					{
						dbg_printf(debug_draw_surface, *(cmd+i));
					}
				}
				break;
		}
		
		if(*cmd >= CMD3D_MIN && *cmd <= CMD3D_MAX)
		{
			ptr += *(cmd+1) + 8;
		}
		else if(*cmd == SVGA_CMD_FENCE)
		{
			//dbg_printf(dbg_cmd_fence);
			ptr += 8;
		}
		else
		{
			//dbg_printf(dbg_cmd_unk, *cmd);
			return;
		}
	}
}
